### PR TITLE
[GEOS-7881] Include Marlin by default. Add support for Windows installer and service.

### PR DESCRIPTION
**Pull request by guischulz**

### CODE REVIEW

**Comment by aaime** [comment]
Hey, thanks a lot it looks good to me, but I don't have much experience with Windows. Did you try both the normal startup and the service installer? You get the Marlin options printout for both cases?

**Comment by guischulz** [comment]
Yes, I tried both options and marlin was enabled.
But I just found an issue when installation to a location with space characters in the path. I will update my pull request soon.

**Comment by guischulz** [comment]
Should be ok now.

**Comment by aaime** [comment]
Awesome, thanks!

**Pull request merged**
